"""
DOC AI - Final Professional Medical Diagnosis Report
Modern, clean, and doctor-friendly design.
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime
import os


def generate_diagnosis_report(diagnosis, user, output_path=None):
    """Generate a clean, modern medical diagnosis report"""
    
    if output_path is None:
        output_path = f"app/static/reports/diagnosis_{diagnosis.id}.pdf"

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    doc = SimpleDocTemplate(output_path, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=60, bottomMargin=60)
    styles = getSampleStyleSheet()

    # Custom Styles
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=26, alignment=1, spaceAfter=12, textColor=colors.darkblue)
    subtitle_style = ParagraphStyle('Subtitle', parent=styles['Heading2'], fontSize=14, alignment=1, textColor=colors.grey, spaceAfter=30)
    heading_style = ParagraphStyle('Heading', parent=styles['Heading2'], fontSize=16, spaceAfter=10, textColor=colors.darkblue)
    normal_style = styles['Normal']
    bold_style = ParagraphStyle('Bold', parent=normal_style, fontName='Helvetica-Bold')

    elements = []

    # Header
    elements.append(Paragraph("🏥 DOC AI", title_style))
    elements.append(Paragraph("AI-Powered Healthcare Diagnosis Report", subtitle_style))
    elements.append(Spacer(1, 20))

    # Patient Information
    elements.append(Paragraph("Patient Information", heading_style))
    patient_data = [
        ["Name", user.name],
        ["Age", f"{user.age} years"],
        ["Gender", user.gender.capitalize()],
        ["Report ID", f"#{diagnosis.id}"],
        ["Generated On", datetime.now().strftime("%d %B %Y, %I:%M %p")]
    ]
    t = Table(patient_data, colWidths=[140, 280])
    t.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 1, colors.lightgrey),
        ('BACKGROUND', (0,0), (0,-1), colors.lightblue),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 25))

    # Final Diagnosis - Highlight Box
    final_conf = diagnosis.confidence_score or 0
    color = colors.green if final_conf >= 70 else colors.orange if final_conf >= 50 else colors.red

    elements.append(Paragraph("Final Diagnosis", heading_style))
    elements.append(Paragraph(f"<font color='{color}'><b>{diagnosis.final_prediction}</b></font>", 
                             ParagraphStyle('Result', parent=styles['Heading1'], fontSize=22, alignment=1)))
    elements.append(Paragraph(f"Confidence Level: <b>{final_conf}%</b>", bold_style))
    elements.append(Spacer(1, 25))

    # Symptom Analysis
    if diagnosis.text_prediction:
        elements.append(Paragraph("Symptom Analysis", heading_style))
        elements.append(Paragraph(f"• Predicted Condition: {diagnosis.text_prediction.get('predicted_disease', 'N/A')}", normal_style))
        elements.append(Paragraph(f"• Confidence: {diagnosis.text_prediction.get('confidence', 0)}%", normal_style))
        elements.append(Spacer(1, 15))

    # Image Analysis
    if diagnosis.image_prediction:
        elements.append(Paragraph("Medical Image Analysis", heading_style))
        elements.append(Paragraph(f"• Detected: {diagnosis.image_prediction.get('predicted_class', 'N/A')}", normal_style))
        elements.append(Paragraph(f"• Confidence: {diagnosis.image_prediction.get('confidence', 0)}%", normal_style))
        elements.append(Spacer(1, 20))

    # Medical Advice
    elements.append(Paragraph("Medical Advice & Recommendation", heading_style))
    elements.append(Paragraph(diagnosis.advice, normal_style))
    elements.append(Spacer(1, 30))

    # Disclaimer
    elements.append(Paragraph("⚠️ IMPORTANT MEDICAL DISCLAIMER", 
                             ParagraphStyle('Disclaimer', parent=styles['Heading3'], textColor=colors.red)))
    elements.append(Paragraph(
        "This report is generated by an Artificial Intelligence system for educational and preliminary assessment purposes only. "
        "It is not a substitute for professional medical advice, diagnosis, or treatment. "
        "Always consult a qualified healthcare professional.", normal_style))

    elements.append(Spacer(1, 40))
    elements.append(Paragraph(f"Generated by DOC AI • {datetime.now().strftime('%d %B %Y at %I:%M %p')}", 
                             ParagraphStyle('Footer', parent=normal_style, fontSize=9, alignment=1, textColor=colors.grey)))

    doc.build(elements)
    return output_path